// hardware configuration
#define SERIAL_USART_TX_PIN GP1

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define SPI_DRIVER SPID1
#define SPI_SCK_PIN GP10
#define SPI_MOSI_PIN GP11
#define SPI_MISO_PIN GP12
#define PMW33XX_CS_PIN GP13

// software configuration

#define SPLIT_USB_TIMEOUT 7000
#define SPLIT_USB_TIMEOUT_POLL 25

#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS

#define COMBO_STRICT_TIMER
#define COMBO_TERM 40
