// hardware configuration
#define SERIAL_USART_TX_PIN GP1

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define SPI_DRIVER SPID1
#define SPI_SCK_PIN GP10
#define SPI_MOSI_PIN GP11
#define SPI_MISO_PIN GP12
#define PMW33XX_CS_PIN GP13

// trackball configuration

#define POINTING_DEVICE_ROTATION_270
#define POINTING_DEVICE_INVERT_Y
#define PMW33XX_CPI 12000
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER 127
#define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 127

// software configuration

#define TAPPING_TERM 150
#define HOLD_ON_OTHER_KEY_PRESS

#define COMBO_STRICT_TIMER
#define COMBO_TERM 60

#define AUTO_SHIFT_TIMEOUT 200
#define NO_AUTO_SHIFT_SPECIAL
#define NO_AUTO_SHIFT_NUMERIC
#define NO_AUTO_SHIFT_ALPHA
#define CAPS_WORD_INVERT_ON_SHIFT
